---
- name: Install haproxy
  package: name=haproxy state=present

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

- name: Enable and start haproxy
  systemd:
    name: haproxy
    state: started
    enabled: yes
    daemon_reload: yes
