---
- include: initialize_groups.yml

- include: evaluate_groups.yml

- hosts: localhost
  tasks:
   - name: 'Get local_secret_token.rb'
     shell: cat /usr/share/foreman/config/initializers/local_secret_token.rb
     delegate_to: "{{ groups.oo_first_master.0 }}"
     register: local_secret_token

   - debug: msg="local_secret_token.rb {{ local_secret_token }}"
